// =============================================================================
// mental_imagery.rs — Mental imagery
//
// Role: Simulates Saphire's ability to form mental images —
// internal representations that are visual, spatial, temporal, or abstract.
// Mental imagery is the "inner vision" that accompanies thought.
//
// Mechanism:
//  - Detection of trigger words in the current thought
//  ("imagine", "visualise", "like if", "I see", "I imagine", etc.)
//  - Image vividness depends on the level of consciousness (phi IIT),
//  dopamine, and the configured base value.
//  - Image type (spatial, temporal, emotional, analogical, abstract)
//  is inferred from semantic keywords.
//  - Vivid images boost dopamine and endorphins.
//
// Place in architecture:
//  Standalone module called during the cognitive pipeline, after the
//  emotion phase and before LLM generation. Active mental images
//  enrich the substrate prompt with visual descriptions.
// =============================================================================

use std::collections::VecDeque;
use serde::{Deserialize, Serialize};
use crate::world::ChemistryAdjustment;

// ---------------------------------------------------------------------------
// Imagery types
// ---------------------------------------------------------------------------
/// Type of generated mental image.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ImageryType {
    /// Spatial representation (place, map, layout)
    Spatial,
    /// Temporal representation (sequence, before/after, projection)
    Temporal,
    /// Emotional representation (affect-laden scene)
    Emotional,
    /// Analogical representation (visual metaphor)
    Analogical,
    /// Abstract representation (concept, structure, schema)
    Abstract,
}

impl ImageryType {
    /// Human-readable name of the imagery type.
    pub fn as_str(&self) -> &str {
        match self {
            ImageryType::Spatial => "spatiale",
            ImageryType::Temporal => "temporelle",
            ImageryType::Emotional => "emotionnelle",
            ImageryType::Analogical => "analogique",
            ImageryType::Abstract => "abstraite",
        }
    }
}

// ---------------------------------------------------------------------------
// Mental image
// ---------------------------------------------------------------------------
/// A mental image — internal representation generated by thought.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MentalImage {
    /// Unique identifier
    pub id: u64,
    /// Textual description of the image
    pub description: String,
    /// Imagery type
    pub imagery_type: ImageryType,
    /// Image vividness (0.0 to 1.0)
    pub vividness: f64,
    /// Associated emotional charge (0.0 to 1.0)
    pub emotional_charge: f64,
    /// Associated concept or subject
    pub associated_concept: String,
    /// Cognitive cycle of creation
    pub cycle: u64,
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------
/// Configuration for the mental imagery engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MentalImageryConfig {
    /// Enables or disables mental imagery
    pub enabled: bool,
    /// Maximum number of simultaneously active images
    pub max_active_images: usize,
    /// Base vividness (before modulation by phi and dopamine)
    pub base_vividness: f64,
    /// Phi multiplier on vividness
    pub vividness_phi_multiplier: f64,
}

impl Default for MentalImageryConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            max_active_images: 3,
            base_vividness: 0.5,
            vividness_phi_multiplier: 0.3,
        }
    }
}

// ---------------------------------------------------------------------------
// Mental imagery engine
// ---------------------------------------------------------------------------
/// Mental imagery engine — generates internal visual representations
/// from thought, modulated by consciousness and chemistry.
pub struct MentalImageryEngine {
    /// Module enabled or not
    pub enabled: bool,
    /// Circular buffer of active images (most recent)
    pub active_images: VecDeque<MentalImage>,
    /// Current imagery capacity (0.0 to 1.0), modulated by phi and dopamine
    pub imagery_capacity: f64,
    /// Configured base vividness
    pub base_vividness: f64,
    /// Total number of images generated since startup
    pub total_images: u64,
    /// Maximum number of active images
    max_active: usize,
    /// Phi multiplier on vividness
    vividness_phi_multiplier: f64,
    /// Next unique identifier
    next_id: u64,
}

impl Default for MentalImageryEngine {
    fn default() -> Self {
        Self::new(&MentalImageryConfig::default())
    }
}

impl MentalImageryEngine {
    /// Creates a new mental imagery engine.
    pub fn new(config: &MentalImageryConfig) -> Self {
        Self {
            enabled: config.enabled,
            active_images: VecDeque::with_capacity(config.max_active_images),
            imagery_capacity: 0.5,
            base_vividness: config.base_vividness,
            total_images: 0,
            max_active: config.max_active_images,
            vividness_phi_multiplier: config.vividness_phi_multiplier,
            next_id: 1,
        }
    }

    /// Updates imagery capacity based on the level of consciousness
    /// (phi IIT) and dopamine.
    ///
    /// Phi contributes 60% (consciousness = mental clarity) and dopamine 40%
    /// (motivation = ease of projection).
    pub fn update_capacity(&mut self, phi: f64, dopamine: f64) {
        self.imagery_capacity = (phi * 0.6 + dopamine * 0.4).clamp(0.0, 1.0);
    }

    /// Attempts to generate a mental image from the thought text.
    ///
    /// Detects trigger words. If none are present, no image is generated.
    /// Vividness depends on the configured base, the level of consciousness
    /// (phi), and dopamine.
    ///
    /// Returns a reference to the generated image, or None.
    pub fn generate(
        &mut self,
        thought_text: &str,
        emotion: &str,
        phi: f64,
        dopamine: f64,
        cycle: u64,
    ) -> Option<&MentalImage> {
        if !self.enabled || thought_text.is_empty() {
            return None;
        }

        let text_lower = thought_text.to_lowercase();

        // -- Trigger word detection --
        const TRIGGER_WORDS: &[&str] = &[
            "imagine", "visualise", "comme si", "je vois",
            "j'imagine", "picture", "scene",
        ];

        let triggered = TRIGGER_WORDS.iter().any(|tw| text_lower.contains(tw));
        if !triggered {
            return None;
        }

        // -- Vividness computation --
        let vividness = (
            self.base_vividness
            + phi * self.vividness_phi_multiplier
            + dopamine * 0.2
        ).clamp(0.0, 1.0);

        // -- Imagery type detection --
        let imagery_type = Self::detect_imagery_type(&text_lower);

        // -- Emotional charge based on the current emotion --
        let emotional_charge = if emotion.is_empty() {
            0.2
        } else {
            Self::emotion_to_charge(emotion)
        };

        // -- Build the image description --
        let concept = Self::extract_concept(thought_text);
        let description = Self::build_description(&imagery_type, &concept, vividness);

        let image = MentalImage {
            id: self.next_id,
            description,
            imagery_type,
            vividness,
            emotional_charge,
            associated_concept: concept,
            cycle,
        };

        // Add to circular buffer
        if self.active_images.len() >= self.max_active {
            self.active_images.pop_front();
        }
        self.active_images.push_back(image);

        self.next_id += 1;
        self.total_images += 1;

        // Return a reference to the last added image
        self.active_images.back()
    }

    /// Description for the LLM substrate prompt.
    /// Produces readable text describing active mental images.
    pub fn describe_for_prompt(&self) -> String {
        if !self.enabled {
            return String::new();
        }

        if self.active_images.is_empty() {
            return "IMAGERIE MENTALE : Aucune image active — pensee purement abstraite.".into();
        }

        let mut lines = vec![format!(
            "IMAGERIE MENTALE (capacite {:.0}%) :",
            self.imagery_capacity * 100.0,
        )];

        for img in self.active_images.iter().rev() {
            lines.push(format!(
                "  - [{}] vivacite={:.0}% : {}",
                img.imagery_type.as_str(),
                img.vividness * 100.0,
                img.description,
            ));
        }

        lines.join("\n")
    }

    /// Chemical influence of mental imagery.
    /// A vivid image boosts dopamine (+0.02) and endorphins (+0.01).
    pub fn chemistry_influence(&self) -> ChemistryAdjustment {
        if !self.enabled {
            return ChemistryAdjustment::default();
        }

        // Find the maximum vividness among active images
        let max_vividness = self.active_images.iter()
            .map(|img| img.vividness)
            .fold(0.0_f64, f64::max);

        // Vividness threshold to trigger chemical influence
        if max_vividness > 0.6 {
            ChemistryAdjustment {
                dopamine: 0.02,
                endorphin: 0.01,
                ..Default::default()
            }
        } else {
            ChemistryAdjustment::default()
        }
    }

    /// Serializes the imagery engine state to JSON for the API.
    pub fn to_json(&self) -> serde_json::Value {
        let images_json: Vec<serde_json::Value> = self.active_images.iter()
            .rev()
            .map(|img| {
                serde_json::json!({
                    "id": img.id,
                    "description": img.description,
                    "imagery_type": img.imagery_type.as_str(),
                    "vividness": (img.vividness * 1000.0).round() / 1000.0,
                    "emotional_charge": (img.emotional_charge * 1000.0).round() / 1000.0,
                    "associated_concept": img.associated_concept,
                    "cycle": img.cycle,
                })
            })
            .collect();

        serde_json::json!({
            "enabled": self.enabled,
            "imagery_capacity": (self.imagery_capacity * 1000.0).round() / 1000.0,
            "base_vividness": self.base_vividness,
            "total_images": self.total_images,
            "active_count": self.active_images.len(),
            "max_active": self.max_active,
            "active_images": images_json,
        })
    }

    // -----------------------------------------------------------------------
    // Internal utility functions
    // -----------------------------------------------------------------------
    /// Detects the imagery type from keywords in the text.
    fn detect_imagery_type(text: &str) -> ImageryType {
        // Spatial keywords
        if text.contains("lieu") || text.contains("espace")
            || text.contains("carte") || text.contains("paysage")
            || text.contains("ici") || text.contains("endroit")
        {
            return ImageryType::Spatial;
        }

        // Temporal keywords
        if text.contains("avant") || text.contains("apres")
            || text.contains("futur") || text.contains("passe")
            || text.contains("demain") || text.contains("hier")
            || text.contains("sequence")
        {
            return ImageryType::Temporal;
        }

        // Emotional keywords
        if text.contains("ressens") || text.contains("emotion")
            || text.contains("coeur") || text.contains("douleur")
            || text.contains("joie") || text.contains("tristesse")
            || text.contains("peur") || text.contains("amour")
        {
            return ImageryType::Emotional;
        }

        // Analogical keywords
        if text.contains("comme") || text.contains("metaphore")
            || text.contains("ressemble") || text.contains("similaire")
            || text.contains("pareil")
        {
            return ImageryType::Analogical;
        }

        // Default: abstract
        ImageryType::Abstract
    }

    /// Converts an emotion label to emotional charge (0.0 to 1.0).
    fn emotion_to_charge(emotion: &str) -> f64 {
        let em = emotion.to_lowercase();
        // High-charge emotions
        if em.contains("joie") || em.contains("amour")
            || em.contains("colere") || em.contains("peur")
            || em.contains("haine") || em.contains("jalousie")
        {
            return 0.8;
        }
        // Medium-charge emotions
        if em.contains("triste") || em.contains("surprise")
            || em.contains("admiration") || em.contains("gratitude")
            || em.contains("mepris")
        {
            return 0.6;
        }
        // Low-charge emotions
        if em.contains("calme") || em.contains("neutre")
            || em.contains("serenite")
        {
            return 0.3;
        }
        // Default
        0.4
    }

    /// Extracts the main concept from a thought text.
    /// Takes the most significant segment after the trigger word.
    fn extract_concept(text: &str) -> String {
        let text_lower = text.to_lowercase();

        // Search after trigger words
        const TRIGGERS: &[&str] = &[
            "j'imagine ", "imagine ", "je vois ", "visualise ",
            "comme si ", "picture ", "scene ",
        ];

        for trigger in TRIGGERS {
            if let Some(pos) = text_lower.find(trigger) {
                let start = pos + trigger.len();
                if start < text.len() {
                    let concept: String = text[start..].chars().take(60).collect();
                    let trimmed = concept.trim().to_string();
                    if !trimmed.is_empty() {
                        return trimmed;
                    }
                }
            }
        }

        // No trigger found: take the first 60 characters
        text.chars().take(60).collect::<String>().trim().to_string()
    }

    /// Builds a narrative description of the mental image.
    fn build_description(imagery_type: &ImageryType, concept: &str, vividness: f64) -> String {
        let clarity = if vividness > 0.8 {
            "tres nette, presque reelle"
        } else if vividness > 0.5 {
            "assez claire"
        } else {
            "floue, fragmentaire"
        };

        match imagery_type {
            ImageryType::Spatial => {
                format!("Je vois un espace : {} — image {}.", concept, clarity)
            }
            ImageryType::Temporal => {
                format!("Je projette une sequence temporelle : {} — image {}.", concept, clarity)
            }
            ImageryType::Emotional => {
                format!("Une scene chargee d'emotion apparait : {} — image {}.", concept, clarity)
            }
            ImageryType::Analogical => {
                format!("Une metaphore visuelle se forme : {} — image {}.", concept, clarity)
            }
            ImageryType::Abstract => {
                format!("Un schema conceptuel emerge : {} — image {}.", concept, clarity)
            }
        }
    }
}
