// =============================================================================
// db/mod.rs — SaphireDb: PostgreSQL connection pool + pgvector
//
// Role: This module manages the entire persistence layer of Saphire.
// It provides a PostgreSQL connection pool (via deadpool) and all
// CRUD operations (Create, Read, Update, Delete) for the various
// tables: memories, identity, thoughts, sessions, neural weights,
// tuning parameters, knowledge, personality profiles, etc.
//
// Dependencies:
//   - deadpool_postgres: asynchronous PostgreSQL connection pool
//   - tokio_postgres: asynchronous PostgreSQL client (no TLS here)
//   - pgvector: PostgreSQL extension for vector search
//   - serde / serde_json: JSON data serialization
//   - chrono: date and time management
//
// Place in the architecture:
//   SaphireDb is owned by the agent (SaphireAgent) and used to
//   persist memories, identity, neural network weights,
//   auto-tuning parameters, and the thought journal.
//   Vector search (pgvector) allows finding memories similar
//   to a new event via cosine distance.
// =============================================================================

mod identity;
mod memories;
mod thoughts;
mod knowledge;
mod tuning;
mod profiling;
mod ethics;
mod orchestrators;
pub mod learnings;
mod connections;
pub mod vectors;
pub mod archives;
pub mod lora;

use deadpool_postgres::{Pool, Manager, ManagerConfig, RecyclingMethod};
use tokio_postgres::NoTls;
use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use crate::neurochemistry::ChemicalSignature;

/// Database layer errors.
/// Three error categories are distinguished to facilitate diagnosis.
#[derive(Debug)]
pub enum DbError {
    /// Connection pool error (no connection available, timeout, etc.)
    Pool(String),
    /// SQL query execution error
    Query(String),
    /// Schema migration execution error
    Migration(String),
}

impl std::fmt::Display for DbError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DbError::Pool(e) => write!(f, "Pool error: {}", e),
            DbError::Query(e) => write!(f, "Query error: {}", e),
            DbError::Migration(e) => write!(f, "Migration error: {}", e),
        }
    }
}

// Automatic conversion of deadpool pool errors to DbError
impl From<deadpool_postgres::PoolError> for DbError {
    fn from(e: deadpool_postgres::PoolError) -> Self {
        DbError::Pool(e.to_string())
    }
}

// Automatic conversion of tokio_postgres errors to DbError
impl From<tokio_postgres::Error> for DbError {
    fn from(e: tokio_postgres::Error) -> Self {
        DbError::Query(e.to_string())
    }
}

/// PostgreSQL database connection configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DbConfig {
    /// PostgreSQL server address (e.g., "localhost", "postgres")
    pub host: String,
    /// PostgreSQL server port (default: 5432)
    pub port: u16,
    /// Username for the connection
    pub user: String,
    /// Password for the connection
    pub password: String,
    /// Database name
    pub dbname: String,
}

impl Default for DbConfig {
    fn default() -> Self {
        Self {
            host: "localhost".into(),
            port: 5432,
            user: "saphire".into(),
            password: "saphire_soul".into(),
            dbname: "saphire_soul".into(),
        }
    }
}

/// A memory stored in the database.
/// Represents an event experienced by the agent with all its metadata
/// (emotion, chemistry, decision, satisfaction, etc.).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryRecord {
    /// Unique identifier of the memory in the database
    pub id: i64,
    /// Textual summary of the memory (generated by the LLM or extracted from the stimulus)
    pub text_summary: String,
    /// Original stimulus data as JSON (danger, reward, etc.)
    pub stimulus_json: serde_json::Value,
    /// Decision taken: -1 (No), 0 (Maybe), 1 (Yes)
    pub decision: i16,
    /// Neurochemical state at the time of the memory (7 neurotransmitters as JSON)
    pub chemistry_json: serde_json::Value,
    /// Dominant emotion at the time of the memory (e.g., "Curiosite", "Peur")
    pub emotion: String,
    /// Mood valence: -1.0 (very negative) to +1.0 (very positive)
    pub mood_valence: f32,
    /// Satisfaction level felt [0.0 - 1.0]
    pub satisfaction: f32,
    /// Emotional weight of the memory (strong memories are better retained)
    pub emotional_weight: f32,
    /// Memory creation date and time (UTC)
    pub created_at: DateTime<Utc>,
    /// Similarity score with a query vector (filled during a search)
    pub similarity: f64,
    /// Chemical signature at the time of encoding (None for old memories)
    pub chemical_signature: Option<ChemicalSignature>,
}

/// New memory to insert into the database.
/// Contains the vector embedding and all associated metadata.
pub struct NewMemory {
    /// Embedding vector (vectorial representation of the content for pgvector)
    pub embedding: Vec<f32>,
    /// Textual summary of the memory
    pub text_summary: String,
    /// Original stimulus data as JSON
    pub stimulus_json: serde_json::Value,
    /// Decision taken: -1 (No), 0 (Maybe), 1 (Yes)
    pub decision: i16,
    /// Neurochemical state as JSON
    pub chemistry_json: serde_json::Value,
    /// Dominant emotion
    pub emotion: String,
    /// Mood valence
    pub mood_valence: f32,
    /// Satisfaction felt
    pub satisfaction: f32,
    /// Emotional weight
    pub emotional_weight: f32,
    /// Optional identifier of the source episodic memory (tier 1 -> tier 2 link)
    pub source_episodic_id: Option<i64>,
    /// Chemical signature at the time of encoding
    pub chemical_signature: Option<ChemicalSignature>,
}

/// PostgreSQL connection pool for Saphire.
/// Wraps the deadpool pool and provides all persistence methods.
pub struct SaphireDb {
    /// The underlying connection pool (max 8 simultaneous connections)
    pub(crate) pool: Pool,
}

impl SaphireDb {
    /// Connects to the PostgreSQL server, creates the connection pool, and runs
    /// schema migrations (creating tables if they do not exist).
    ///
    /// # Parameters
    /// - `config`: connection configuration (host, port, user, password, dbname)
    ///
    /// # Returns
    /// - `Ok(SaphireDb)`: the connection pool ready for use
    /// - `Err(DbError)`: connection or migration error
    pub async fn connect(config: &DbConfig) -> Result<Self, DbError> {
        let mut pg_config = tokio_postgres::Config::new();
        pg_config.host(&config.host);
        pg_config.port(config.port);
        pg_config.user(&config.user);
        pg_config.password(&config.password);
        pg_config.dbname(&config.dbname);

        // Connection recycling manager configuration.
        // RecyclingMethod::Fast: reuses connections without costly verification.
        let mgr_config = ManagerConfig {
            recycling_method: RecyclingMethod::Fast,
        };
        let mgr = Manager::from_config(pg_config, NoTls, mgr_config);
        let pool = Pool::builder(mgr)
            .max_size(8) // Maximum 8 simultaneous connections in the pool
            .build()
            .map_err(|e| DbError::Pool(e.to_string()))?;

        let db = Self { pool };
        // Run migrations to create/update the schema
        db.run_migrations().await?;
        Ok(db)
    }

    /// Runs SQL migrations from the embedded schema.sql file.
    /// Uses IF NOT EXISTS to be idempotent (can be run multiple times).
    async fn run_migrations(&self) -> Result<(), DbError> {
        let client = self.pool.get().await?;
        client.batch_execute(include_str!("../../sql/schema.sql")).await
            .map_err(|e| DbError::Migration(e.to_string()))?;
        Ok(())
    }

    /// Checks that the database connection is functional.
    /// Useful for health checks and monitoring.
    ///
    /// # Returns
    /// true if the connection is operational, false otherwise
    pub async fn health_check(&self) -> bool {
        match self.pool.get().await {
            Ok(client) => client.query_one("SELECT 1", &[]).await.is_ok(),
            Err(_) => false,
        }
    }

    /// Statistics for the main database tables.
    pub async fn table_stats(&self) -> Result<serde_json::Value, DbError> {
        let client = self.pool.get().await?;

        let tables = [
            "memories", "self_identity", "personality_traits",
            "thought_log", "founding_memories", "session_log",
            "tuning_params", "bandit_arms", "knowledge_log", "episodic_memories",
            "ocean_self_profile", "human_profiles",
            "personal_ethics", "personal_ethics_history",
            "dream_journal", "desires", "lessons", "wounds", "nn_learnings",
            "neural_connections", "sleep_history", "memory_vectors",
            "memory_archives", "lora_training_data",
        ];

        let mut stats = serde_json::Map::new();
        for table in &tables {
            let query = format!("SELECT COUNT(*) FROM {}", table);
            match client.query_one(&query, &[]).await {
                Ok(row) => {
                    let count: i64 = row.get(0);
                    stats.insert(table.to_string(), serde_json::json!(count));
                }
                Err(_) => {
                    stats.insert(table.to_string(), serde_json::json!(-1));
                }
            }
        }
        Ok(serde_json::Value::Object(stats))
    }
}
