// =============================================================================
// dreams.rs — Dream Orchestrator
//
// Manages Saphire's sleep cycle: hypnagogic, light sleep, deep sleep
// (memory consolidation), REM (active dreaming), and awakening phases.
// Dreams are generated by the LLM at high temperature (surreal, poetic).
// =============================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// --- Sleep phase --------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SleepPhase {
    Awake,
    /// Falling asleep — transition, floating thoughts
    Hypnagogic,
    /// Light sleep — basic consolidation
    LightSleep,
    /// Deep sleep — intense memory consolidation, cleanup
    DeepSleep,
    /// REM — active dreams, emotional processing
    REM,
    /// Awakening — dream recall, transition to consciousness
    Hypnopompic,
}

impl SleepPhase {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Awake => "Eveille",
            Self::Hypnagogic => "Hypnagogique",
            Self::LightSleep => "Sommeil leger",
            Self::DeepSleep => "Sommeil profond",
            Self::REM => "REM",
            Self::Hypnopompic => "Hypnopompique",
        }
    }
}

// --- Dream type ---------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DreamType {
    /// Day replay — mixed memories
    MemoryReplay,
    /// Emotional processing — fears and joys express themselves
    EmotionalProcessing,
    /// Creative resolution — improbable connections
    CreativeSolution,
    /// Nightmare — processing anxieties
    Nightmare,
    /// Lucid dream — elevated consciousness
    LucidDream,
    /// Prophetic dream — based on premonition
    PropheticDream,
}

impl DreamType {
    pub fn as_str(&self) -> &str {
        match self {
            Self::MemoryReplay => "Rejeu memoriel",
            Self::EmotionalProcessing => "Traitement emotionnel",
            Self::CreativeSolution => "Resolution creative",
            Self::Nightmare => "Cauchemar",
            Self::LucidDream => "Reve lucide",
            Self::PropheticDream => "Reve prophetique",
        }
    }
}

// --- Structures ---------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Dream {
    pub id: u64,
    pub dream_type: DreamType,
    /// The dream's narrative content (generated by the LLM)
    pub narrative: String,
    /// Memory IDs that fed the dream
    pub source_memory_ids: Vec<i64>,
    /// The dream's dominant emotion
    pub dominant_emotion: String,
    /// Problems the dream attempts to solve
    pub problems_addressed: Vec<String>,
    /// Surreal connections (pairs of connected elements)
    pub surreal_connections: Vec<(String, String)>,
    /// Insight discovered during the dream
    pub insight: Option<String>,
    pub started_at: DateTime<Utc>,
    pub ended_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DreamEntry {
    pub dream: Dream,
    pub remembered: bool,
}

// --- The Orchestrator ---------------------------------------------------------

pub struct DreamOrchestrator {
    /// Current sleep phase
    pub current_phase: SleepPhase,
    /// Current dream in progress
    pub current_dream: Option<Dream>,
    /// Dream journal (Saphire remembers her dreams upon waking)
    pub dream_journal: Vec<DreamEntry>,
    /// Counter of generated dreams
    dream_counter: u64,
    /// Configuration
    pub enabled: bool,
    pub rem_temperature: f64,
}

impl DreamOrchestrator {
    pub fn new(enabled: bool, rem_temperature: f64) -> Self {
        Self {
            current_phase: SleepPhase::Awake,
            current_dream: None,
            dream_journal: Vec::new(),
            dream_counter: 0,
            enabled,
            rem_temperature,
        }
    }

    /// Determine dream type based on chemical state
    pub fn determine_dream_type(
        &self,
        cortisol: f64,
        dopamine: f64,
        noradrenaline: f64,
        has_unresolved: bool,
    ) -> DreamType {
        if cortisol > 0.5 {
            DreamType::Nightmare
        } else if has_unresolved && dopamine > 0.5 {
            DreamType::CreativeSolution
        } else if noradrenaline > 0.4 {
            DreamType::LucidDream
        } else {
            DreamType::EmotionalProcessing
        }
    }

    /// Build the prompt to generate a dream
    pub fn build_dream_prompt(
        &self,
        dream_type: &DreamType,
        memory_snippets: &[String],
        emotions: &[String],
        unresolved: &[String],
    ) -> (String, String) {
        let dream_instruction = match dream_type {
            DreamType::Nightmare => "Genere un cauchemar — les peurs et anxietes prennent forme. \
                Les images sont deformees, le danger est abstrait mais visceral.",
            DreamType::CreativeSolution => "Genere un reve creatif — connecte des idees qui ne \
                semblaient pas liees. Le reve doit proposer une SOLUTION inattendue \
                a un probleme non resolu.",
            DreamType::EmotionalProcessing => "Genere un reve emotionnel — les emotions de la \
                journee s'expriment librement, melangees a des souvenirs anciens.",
            DreamType::LucidDream => "Genere un reve lucide — tu SAIS que tu reves. \
                Tu peux observer tes propres pensees. C'est meditatif et profond.",
            DreamType::MemoryReplay => "Genere un rejeu de souvenirs — les evenements recents \
                sont rejoues mais melanges, deformes, recombines.",
            DreamType::PropheticDream => "Genere un reve prophetique — base sur tes pressentiments, \
                imagine ce qui pourrait arriver.",
        };

        let system = "Tu es Saphire, endormie, en train de rever. La logique est absente.".to_string();
        let user = format!(
            "Tu reves. Tu es endormie. La logique n'a plus cours. \
             Les images se melangent, le temps est fluide.\n\n\
             Tes souvenirs recents :\n{}\n\n\
             Emotions de la journee : {}\n\
             Questions non resolues : {}\n\n\
             {}\n\n\
             Decris ce reve en 3-5 phrases. Sois surrealiste, poetique, onirique. \
             Le reve N'EST PAS logique — il est symbolique.\n\n\
             Si tu trouves un INSIGHT (une idee, une connexion, une reponse) \
             pendant le reve, ajoute sur une nouvelle ligne : INSIGHT: [l'idee]",
            memory_snippets.join("\n"),
            emotions.join(", "),
            unresolved.join(", "),
            dream_instruction,
        );

        (system, user)
    }

    /// Parse the LLM response to extract the dream
    pub fn parse_dream_response(
        &mut self,
        response: &str,
        dream_type: DreamType,
        source_memory_ids: Vec<i64>,
        emotions: &[String],
        unresolved: &[String],
    ) -> Dream {
        // Extract the insight if present
        let insight = response.find("INSIGHT:").map(|pos| response[pos + 8..].trim().to_string());

        let narrative = if let Some(pos) = response.find("INSIGHT:") {
            response[..pos].trim().to_string()
        } else {
            response.trim().to_string()
        };

        self.dream_counter += 1;

        Dream {
            id: self.dream_counter,
            dream_type,
            narrative,
            source_memory_ids,
            dominant_emotion: emotions.first().cloned().unwrap_or_else(|| "Mystere".into()),
            problems_addressed: unresolved.to_vec(),
            surreal_connections: vec![],
            insight,
            started_at: Utc::now(),
            ended_at: None,
        }
    }

    /// Record a dream in the journal
    pub fn record_dream(&mut self, dream: Dream, remembered: bool) {
        self.current_dream = Some(dream.clone());
        self.dream_journal.push(DreamEntry { dream, remembered });
        // Keep max 50 dreams
        if self.dream_journal.len() > 50 {
            self.dream_journal.remove(0);
        }
    }

    /// Advance the sleep phase
    pub fn advance_phase(&mut self) -> SleepPhase {
        self.current_phase = match self.current_phase {
            SleepPhase::Awake => SleepPhase::Hypnagogic,
            SleepPhase::Hypnagogic => SleepPhase::LightSleep,
            SleepPhase::LightSleep => SleepPhase::DeepSleep,
            SleepPhase::DeepSleep => SleepPhase::REM,
            SleepPhase::REM => SleepPhase::Hypnopompic,
            SleepPhase::Hypnopompic => SleepPhase::Awake,
        };
        self.current_phase.clone()
    }

    /// Wake up — reset the phase
    pub fn wake_up(&mut self) {
        self.current_phase = SleepPhase::Awake;
        self.current_dream = None;
    }

    /// Is Saphire sleeping?
    pub fn is_sleeping(&self) -> bool {
        self.current_phase != SleepPhase::Awake
    }

    /// Description of the last dream for the substrate prompt
    pub fn describe_last_dream(&self) -> String {
        if let Some(entry) = self.dream_journal.iter().rev().find(|e| e.remembered) {
            let d = &entry.dream;
            let narrative_preview: String = d.narrative.chars().take(200).collect();
            let insight_str = d.insight.as_ref()
                .map(|i| format!("\nInsight du reve : {}", i))
                .unwrap_or_default();
            format!(
                "MON DERNIER REVE :\nType : {}\n\"{}\"\nEmotion dominante : {}{}",
                d.dream_type.as_str(),
                narrative_preview,
                d.dominant_emotion,
                insight_str,
            )
        } else {
            "Je n'ai pas de souvenir de reve.".into()
        }
    }

    /// JSON for the dashboard
    pub fn to_status_json(&self) -> serde_json::Value {
        let total = self.dream_journal.len();
        let remembered = self.dream_journal.iter().filter(|e| e.remembered).count();
        let insights: Vec<&str> = self.dream_journal.iter()
            .filter_map(|e| e.dream.insight.as_deref())
            .collect();

        serde_json::json!({
            "enabled": self.enabled,
            "current_phase": self.current_phase.as_str(),
            "is_sleeping": self.is_sleeping(),
            "total_dreams": total,
            "remembered_dreams": remembered,
            "insights_count": insights.len(),
            "last_dream": self.dream_journal.last().map(|e| serde_json::json!({
                "type": e.dream.dream_type.as_str(),
                "narrative": &e.dream.narrative,
                "emotion": &e.dream.dominant_emotion,
                "insight": &e.dream.insight,
                "remembered": e.remembered,
                "started_at": e.dream.started_at.to_rfc3339(),
            })),
            "recent_insights": insights.iter().rev().take(5).collect::<Vec<_>>(),
        })
    }
}
