// =============================================================================
// plugins/mod.rs — Plugin system (Plugin trait + events)
//
// Role: This file defines Saphire's extensible plugin system.
// It contains the Plugin trait, brain events (BrainEvent),
// possible plugin actions (PluginAction), and the plugin manager
// (PluginManager) that orchestrates event broadcasting.
//
// Dependencies:
//   - serde: serialization of events and actions for JSON transport
//
// Place in architecture:
//   The PluginManager is owned by the agent (SaphireAgent). At each brain
//   cycle, events are broadcast to all registered plugins. Each plugin
//   can react by returning actions (adjust chemistry, store a memory,
//   broadcast a WebSocket message, etc.).
//   This design pattern decouples the cognitive core from extensions.
// =============================================================================

// ─── Available plugin sub-modules ─────────────────────────────────────────────

/// Web interface plugin (axum + WebSocket): serializes brain events
/// and broadcasts them to connected WebSocket clients.
pub mod web_ui;

/// Micro neural network plugin: a small MLP (Multi-Layer Perceptron)
/// that locally learns to predict satisfaction.
pub mod micro_nn;

/// Vector memory plugin: stores embeddings in RAM and computes
/// the emergent personality from memory emotions.
pub mod vector_memory;

use serde::{Deserialize, Serialize};

/// Events emitted by Saphire's brain at each important step.
/// Plugins subscribe to these events to react accordingly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BrainEvent {
    /// A stimulus has been analyzed by the NLP (Natural Language Processing) module.
    StimulusAnalyzed {
        /// Text of the analyzed stimulus
        text: String,
        /// Detected danger level [0.0 - 1.0]
        danger: f64,
        /// Detected reward level [0.0 - 1.0]
        reward: f64,
        /// Detected dominant emotion
        emotion: String,
    },
    /// A decision has been made by the module consensus.
    DecisionMade {
        /// Decision as text ("Oui", "Non", "Peut-etre")
        decision: String,
        /// Decision score [-1.0 to +1.0]
        score: f64,
        /// Satisfaction level after the decision [0.0 - 1.0]
        satisfaction: f64,
    },
    /// A complete brain cycle has finished.
    CycleCompleted {
        /// Cycle number
        cycle: u64,
        /// Dominant emotion at the end of the cycle
        emotion: String,
        /// Consciousness level at the end of the cycle [0.0 - 1.0]
        consciousness: f64,
    },
    /// The neurochemical state has changed significantly.
    ChemistryChanged {
        /// The 7 neurotransmitters in order:
        /// [dopamine, cortisol, serotonin, adrenaline, oxytocin, endorphin, noradrenaline]
        chemistry: [f64; 7],
    },
    /// An autonomous thought has been generated by the LLM.
    ThoughtEmitted {
        /// Thought type (e.g., "introspection", "exploration", "reverie")
        thought_type: String,
        /// Text content of the thought
        content: String,
    },
    /// The agent's boot process has completed.
    BootCompleted {
        /// true if this is the very first boot (genesis), false otherwise
        is_genesis: bool,
    },
    /// The agent shutdown has begun (saving in progress).
    ShutdownStarted,
    /// The agent's identity has been updated (self-description modified).
    IdentityUpdated {
        /// New identity description
        description: String,
    },
}

/// Actions that a plugin can request from the brain in response to an event.
/// The PluginManager collects all actions and forwards them to the agent.
#[derive(Debug, Clone)]
pub enum PluginAction {
    /// Adjust a neurotransmitter (add a delta to the current value).
    AdjustChemistry {
        /// Molecule name (e.g., "dopamine", "cortisol")
        molecule: String,
        /// Variation to apply (positive = increase, negative = decrease)
        delta: f64,
    },
    /// Store a memory.
    StoreMemory {
        /// Memory text
        text: String,
        /// Associated emotion
        emotion: String,
        /// Memory importance [0.0 - 1.0] (influences emotional weight)
        importance: f64,
    },
    /// Broadcast a message via WebSocket to all connected clients.
    WebSocketBroadcast {
        /// JSON data to broadcast
        data: String,
    },
    /// Write a message to the logs.
    Log {
        /// Message to record
        message: String,
    },
    /// No action to perform.
    None,
}

/// Trait that every plugin must implement.
/// A plugin has a name and reacts to brain events by returning
/// a list of actions to perform.
pub trait Plugin: Send {
    /// Returns the plugin name (used for logs and identification).
    fn name(&self) -> &str;

    /// Reacts to a brain event.
    /// Receives an event and returns a list of actions to perform.
    ///
    /// # Parameters
    /// - `event`: the event emitted by the brain
    ///
    /// # Returns
    /// List of actions to perform (can be empty)
    fn on_event(&mut self, event: &BrainEvent) -> Vec<PluginAction>;
}

/// Plugin manager.
/// Registers plugins and broadcasts brain events to each of them.
pub struct PluginManager {
    /// List of registered plugins (heap-allocated trait objects)
    plugins: Vec<Box<dyn Plugin>>,
}

impl Default for PluginManager {
    fn default() -> Self {
        Self::new()
    }
}

impl PluginManager {
    /// Creates a new empty plugin manager.
    pub fn new() -> Self {
        Self { plugins: Vec::new() }
    }

    /// Registers a new plugin in the manager.
    /// The plugin is immediately active and will receive upcoming events.
    ///
    /// # Parameters
    /// - `plugin`: the plugin to register (boxed for dynamic polymorphism)
    pub fn register(&mut self, plugin: Box<dyn Plugin>) {
        println!("  [Plugin] Enregistré : {}", plugin.name());
        self.plugins.push(plugin);
    }

    /// Broadcasts an event to all registered plugins.
    /// Collects and returns all actions requested by the plugins.
    ///
    /// # Parameters
    /// - `event`: the brain event to broadcast
    ///
    /// # Returns
    /// Concatenated list of all actions requested by all plugins
    pub fn broadcast(&mut self, event: &BrainEvent) -> Vec<PluginAction> {
        let mut all_actions = Vec::new();
        for plugin in &mut self.plugins {
            let actions = plugin.on_event(event);
            all_actions.extend(actions);
        }
        all_actions
    }
}
