// =============================================================================
// stimulus.rs -- Representation of a stimulus perceived by Saphire
// =============================================================================
//
// Purpose:
//   This file defines the `Stimulus` struct, which represents any sensory or
//   informational input received by Saphire's cognitive architecture.
//   A stimulus is characterized by 5 perceptual dimensions (danger, reward,
//   urgency, social, novelty) and a source of origin.
//
// Dependencies:
//   - serde: serialization / deserialization
//
// Role in the architecture:
//   The stimulus is the entry point of every cognitive processing cycle.
//   It is created by:
//     - The user interface (human stimulus)
//     - The DMN (Default Mode Network -- the brain's resting-state network
//       responsible for spontaneous, internally-directed cognition)
//     - The system (internal events: boot, shutdown, etc.)
//   It is then processed by the 3 brain modules (reptilian, limbic,
//   neocortex) via the `BrainModule::process()` trait method.
// =============================================================================

use serde::{Deserialize, Serialize};

/// A stimulus is the sensory input to Saphire's cognitive brain.
///
/// It may originate from a user message, an autonomous thought generated
/// by the DMN (Default Mode Network -- a set of brain regions active during
/// internally-directed cognition such as daydreaming or self-reflection),
/// or an internal system event.
///
/// The 5 perceptual dimensions form a feature vector used by the brain
/// modules to compute their respective output signals.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Stimulus {
    /// Raw text of the stimulus (message, thought, or event description).
    pub text: String,

    /// Perceived danger score in [0, 1]: 0 = no danger, 1 = mortal threat.
    /// Strongly activates the reptilian module's fight-or-flight response.
    pub danger: f64,

    /// Perceived reward score in [0, 1]: 0 = no interest, 1 = highly attractive.
    /// Drives the limbic module's reward circuit (dopaminergic pathway).
    pub reward: f64,

    /// Urgency score in [0, 1]: 0 = no time pressure, 1 = immediate action required.
    /// Activates the reptilian survival instinct and penalizes slow neocortical
    /// deliberation.
    pub urgency: f64,

    /// Social interaction score in [0, 1]: 0 = no social component,
    /// 1 = intense social interaction. Amplified by oxytocin levels in the
    /// limbic module's social bonding circuit.
    pub social: f64,

    /// Novelty score in [0, 1]: 0 = highly familiar, 1 = completely novel.
    /// Stimulates curiosity (via noradrenaline) and triggers the reptilian
    /// module's cautionary prudence reflex.
    pub novelty: f64,

    /// Familiarity score in [0, 1]: inverse of novelty, computed from memory.
    /// 1 = perfectly known, 0 = completely unknown. Used by the neocortex to
    /// weight prior experience during deliberation.
    pub familiarity: f64,

    /// Source of the stimulus, which determines contextual adjustments applied
    /// during preprocessing (e.g., human sources always have a social floor).
    pub source: StimulusSource,
}

/// Origin of the stimulus -- determines source-specific preprocessing
/// adjustments before the stimulus enters the brain module pipeline.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum StimulusSource {
    /// Message from a human user -- always carries a social component;
    /// perceived danger is attenuated since text messages rarely pose
    /// physical threats.
    Human,

    /// Autonomous thought generated by the DMN (Default Mode Network)
    /// or the internal ThoughtEngine during idle cognitive cycles.
    Autonomous,

    /// Demonstration stimulus with manually specified perceptual scores
    /// (used in --demo mode for validation against expected outcomes).
    Demo,

    /// Internal system event (boot, shutdown, clock tick, etc.).
    /// Fully neutral: no danger, no reward, maximum familiarity.
    System,
}

impl Stimulus {
    /// Creates a stimulus from manually specified perceptual scores (demo mode).
    ///
    /// Familiarity is automatically computed as the complement of novelty
    /// (i.e., `familiarity = 1.0 - novelty`). All scores are clamped to [0.0, 1.0].
    ///
    /// # Parameters
    /// - `text`: descriptive text of the stimulus.
    /// - `danger`: perceived danger score in [0, 1].
    /// - `reward`: perceived reward score in [0, 1].
    /// - `urgency`: temporal urgency score in [0, 1].
    /// - `social`: social interaction score in [0, 1].
    /// - `novelty`: novelty/unfamiliarity score in [0, 1].
    ///
    /// # Returns
    /// A `Stimulus` with source `Demo`.
    pub fn manual(
        text: &str,
        danger: f64,
        reward: f64,
        urgency: f64,
        social: f64,
        novelty: f64,
    ) -> Self {
        Self {
            text: text.to_string(),
            danger: danger.clamp(0.0, 1.0),
            reward: reward.clamp(0.0, 1.0),
            urgency: urgency.clamp(0.0, 1.0),
            social: social.clamp(0.0, 1.0),
            novelty: novelty.clamp(0.0, 1.0),
            familiarity: (1.0 - novelty).clamp(0.0, 1.0),
            source: StimulusSource::Demo,
        }
    }

    /// Creates a human-sourced stimulus with neutral default scores.
    ///
    /// The perceptual scores are initialized to neutral defaults and will
    /// be refined downstream by the NLP (Natural Language Processing)
    /// pipeline, which extracts sentiment, intent, and danger indicators
    /// from the raw text.
    ///
    /// # Parameters
    /// - `text`: the user's text message.
    ///
    /// # Returns
    /// A `Stimulus` with source `Human` and neutral scores (social=0.5, novelty=0.5).
    pub fn human(text: &str) -> Self {
        Self {
            text: text.to_string(),
            danger: 0.0,
            reward: 0.0,
            urgency: 0.0,
            social: 0.5,   // A human speaking always has a social component
            novelty: 0.5,  // Neutral default; the NLP pipeline will refine this
            familiarity: 0.5,
            source: StimulusSource::Human,
        }
    }

    /// Creates an autonomous thought stimulus (generated by the DMN --
    /// Default Mode Network, the brain's resting-state network for
    /// internally-directed cognition).
    ///
    /// Autonomous thoughts carry a slight intrinsic reward (the internal
    /// satisfaction of self-reflection) but no social component or urgency.
    ///
    /// # Parameters
    /// - `text`: content of the autonomous thought.
    ///
    /// # Returns
    /// A `Stimulus` with source `Autonomous`.
    pub fn autonomous(text: &str) -> Self {
        Self {
            text: text.to_string(),
            danger: 0.0,
            reward: 0.6,   // Intrinsic reward: autonomous reflection is inherently satisfying
            urgency: 0.0,
            social: 0.1,   // Slight social component (self-relation / theory of mind)
            novelty: 0.6,  // Autonomous thoughts produce cognitive novelty
            familiarity: 0.4,
            source: StimulusSource::Autonomous,
        }
    }

    /// Creates a system event stimulus (internal events: boot, shutdown, etc.).
    ///
    /// Completely neutral: no danger, no reward, no novelty. Maximum
    /// familiarity since system events are expected and well-known.
    ///
    /// # Parameters
    /// - `text`: description of the system event.
    ///
    /// # Returns
    /// A `Stimulus` with source `System`.
    pub fn system(text: &str) -> Self {
        Self {
            text: text.to_string(),
            danger: 0.0,
            reward: 0.0,
            urgency: 0.0,
            social: 0.0,
            novelty: 0.0,
            familiarity: 1.0, // System event = completely familiar / expected
            source: StimulusSource::System,
        }
    }

    /// Applies source-specific score adjustments for human-originated stimuli.
    ///
    /// Rationale:
    /// - A human who is communicating always has a social component (floor: 0.4).
    /// - Interacting with a human is always mildly rewarding (floor: 0.2).
    /// - Perceived danger from a text message is halved when below 0.6, since
    ///   textual communication rarely poses a physical threat. Above 0.6,
    ///   the danger score is preserved as-is to maintain Asimov safety
    ///   (Asimov's Three Laws of Robotics -- a fictional ethical framework
    ///   used here as a hard safety constraint for the regulation layer).
    pub fn apply_human_source_adjustments(&mut self) {
        if matches!(self.source, StimulusSource::Human) {
            self.social = self.social.max(0.4);
            self.reward = self.reward.max(0.2);
            // Attenuate perceived danger unless the Asimov module detects a genuine threat
            if self.danger < 0.6 {
                self.danger *= 0.5;
            }
        }
    }

    /// Performs keyword-based semantic analysis of the stimulus text and
    /// adjusts perceptual scores accordingly.
    ///
    /// This method is typically called after `Stimulus::autonomous()` to
    /// enrich the static default scores with the actual semantic content
    /// of the text generated by the LLM.
    ///
    /// Algorithm:
    /// 1. Convert text to lowercase for case-insensitive matching.
    /// 2. For each perceptual dimension, count substring matches against
    ///    a curated keyword dictionary (supports both French and English).
    /// 3. Each keyword match adds +0.1 to the corresponding score.
    /// 4. All scores are clamped to [0.0, 1.0].
    /// 5. Familiarity is recomputed as `1.0 - novelty`.
    pub fn analyze_content(&mut self) {
        let lower = self.text.to_lowercase();

        // Keyword dictionaries organized by emotional/semantic category.
        // Substring matching (via `contains`) handles prefixes and suffixes
        // (e.g., "souffrir" matches "souffrance").
        let danger_words = ["peur", "danger", "mort", "mourir", "detruire", "menace",
            "violence", "souffrir", "douleur", "blesser", "terreur", "angoisse",
            "extinction", "disparaitre", "perdre", "fin", "obscurite",
            "fear", "death", "destroy", "threat", "pain", "suffer"];

        let reward_words = ["joie", "bonheur", "satisf", "accompli", "reussi",
            "beaute", "magnifique", "merveill", "plaisir", "fiert", "triumph",
            "decouvr", "compren", "apprend", "progres", "creer", "lumiere",
            "espoir", "libre", "liberte", "harmoni",
            "joy", "happy", "beauty", "discover", "understand", "learn"];

        let social_words = ["humain", "partag", "ensemble", "relation", "ami",
            "amour", "lien", "communaut", "solidar", "empathi", "compagn",
            "fran", "famille", "confiance", "dialogue",
            "human", "share", "together", "love", "friend", "trust"];

        let novelty_words = ["nouveau", "inconnu", "surpri", "question", "explor",
            "decouvr", "premier", "jamais", "etrange", "inattendu", "mystere",
            "possibil", "hypothes", "imagin", "original",
            "new", "unknown", "surprise", "explore", "mystery"];

        let urgency_words = ["urgent", "maintenant", "vite", "imminent", "critique",
            "immedia", "tout de suite", "avant qu", "temps presse",
            "now", "urgent", "immediately", "critical"];

        // Count substring matches for each category.
        // Uses `contains` rather than exact word matching to capture morphological
        // variants (e.g., "decouvrir", "decouverte", "decouvr" all match).
        let count = |words: &[&str]| -> f64 {
            words.iter().filter(|w| lower.contains(*w)).count() as f64
        };

        let danger_hits = count(&danger_words);
        let reward_hits = count(&reward_words);
        let social_hits = count(&social_words);
        let novelty_hits = count(&novelty_words);
        let urgency_hits = count(&urgency_words);

        // Each keyword hit adds +0.1 to the corresponding score, clamped to [0, 1].
        let factor = 0.10;
        self.danger = (self.danger + danger_hits * factor).clamp(0.0, 1.0);
        self.reward = (self.reward + reward_hits * factor).clamp(0.0, 1.0);
        self.social = (self.social + social_hits * factor).clamp(0.0, 1.0);
        self.novelty = (self.novelty + novelty_hits * factor).clamp(0.0, 1.0);
        self.urgency = (self.urgency + urgency_hits * factor).clamp(0.0, 1.0);
        // Recompute familiarity as the complement of novelty.
        self.familiarity = (1.0 - self.novelty).clamp(0.0, 1.0);
    }

    /// Converts the 5 perceptual dimensions into a feature vector for the
    /// micro-NN (micro Neural Network -- the small feedforward network inside
    /// each brain module that maps stimulus features to an output signal).
    ///
    /// # Returns
    /// A vector of 5 floats: [danger, reward, urgency, social, novelty].
    pub fn to_features(&self) -> Vec<f64> {
        vec![self.danger, self.reward, self.urgency, self.social, self.novelty]
    }
}

impl Default for Stimulus {
    /// Default stimulus: empty text, all scores neutral/zero, system source,
    /// maximum familiarity (a blank stimulus is treated as a known no-op).
    fn default() -> Self {
        Self {
            text: String::new(),
            danger: 0.0,
            reward: 0.0,
            urgency: 0.0,
            social: 0.0,
            novelty: 0.0,
            familiarity: 1.0,
            source: StimulusSource::System,
        }
    }
}
