// =============================================================================
// stimulus.rs — Representation of a stimulus perceived by Saphire
// =============================================================================
//
// Role: This file defines the `Stimulus` structure, which represents any
// sensory or informational input received by Saphire's brain.
// A stimulus is characterized by 5 perceptual dimensions (danger,
// reward, urgency, social, novelty) and a source of origin.
//
// Dependencies:
//   - serde : serialization / deserialization
//
// Place in architecture:
//   The stimulus is the entry point of each processing cycle.
//   It is created by:
//   - The user interface (human stimulus)
//   - The DMN (Default Mode Network, autonomous thoughts)
//   - The system (internal events: boot, shutdown, etc.)
//   It is then processed by the 3 brain modules (reptilian, limbic,
//   neocortex) via the `BrainModule::process()` trait.
// =============================================================================

use serde::{Deserialize, Serialize};

/// A stimulus is the sensory input to Saphire's brain.
/// It can come from a user message, an autonomous thought generated by
/// the DMN (Default Mode Network), or an internal system event.
///
/// The 5 perceptual dimensions form a feature vector used by the brain
/// modules to compute their signal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Stimulus {
    /// Raw text of the stimulus (message, thought, event)
    pub text: String,
    /// Perceived danger score [0, 1]: 0 = no danger, 1 = mortal danger.
    /// Strongly influences the reptilian module.
    pub danger: f64,
    /// Perceived reward score [0, 1]: 0 = no interest, 1 = very attractive.
    /// Influences the reward circuit of the limbic module.
    pub reward: f64,
    /// Urgency score [0, 1]: 0 = no time pressure, 1 = immediate.
    /// Activates the survival instinct of the reptilian and penalizes the neocortex.
    pub urgency: f64,
    /// Social score (human interaction) [0, 1]: 0 = no social component,
    /// 1 = intense social interaction. Amplified by oxytocin in the limbic module.
    pub social: f64,
    /// Novelty score [0, 1]: 0 = very familiar, 1 = completely new.
    /// Stimulates curiosity (noradrenaline) and the prudence instinct.
    pub novelty: f64,
    /// Familiarity [0, 1]: inverse of novelty, computed by memory.
    /// 1 = perfectly known, 0 = completely unknown.
    pub familiarity: f64,
    /// Stimulus source: determines the contextual adjustments applied
    pub source: StimulusSource,
}

/// Origin of the stimulus — allows adapting processing according to the source.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum StimulusSource {
    /// Message from a human — always social, reduced danger
    Human,
    /// Autonomous thought generated by the DMN (Default Mode Network)
    /// or the ThoughtEngine
    Autonomous,
    /// Demo stimulus (demo mode with manual scores)
    Demo,
    /// Internal system event (boot, shutdown, clock, etc.)
    System,
}

impl Stimulus {
    /// Creates a stimulus from manual scores (demo mode).
    /// Familiarity is automatically computed as the inverse of novelty.
    /// All scores are clamped between 0.0 and 1.0.
    ///
    /// # Parameters
    /// - `text` : descriptive text of the stimulus.
    /// - `danger` : perceived danger score [0, 1].
    /// - `reward` : perceived reward score [0, 1].
    /// - `urgency` : urgency score [0, 1].
    /// - `social` : social component score [0, 1].
    /// - `novelty` : novelty score [0, 1].
    ///
    /// # Returns
    /// A `Stimulus` with source `Demo`.
    pub fn manual(
        text: &str,
        danger: f64,
        reward: f64,
        urgency: f64,
        social: f64,
        novelty: f64,
    ) -> Self {
        Self {
            text: text.to_string(),
            danger: danger.clamp(0.0, 1.0),
            reward: reward.clamp(0.0, 1.0),
            urgency: urgency.clamp(0.0, 1.0),
            social: social.clamp(0.0, 1.0),
            novelty: novelty.clamp(0.0, 1.0),
            familiarity: (1.0 - novelty).clamp(0.0, 1.0),
            source: StimulusSource::Demo,
        }
    }

    /// Creates a human stimulus with neutral default scores.
    /// The scores will then be filled by the NLP pipeline
    /// (Natural Language Processing).
    ///
    /// # Parameters
    /// - `text` : the user's text message.
    ///
    /// # Returns
    /// A `Stimulus` with source `Human` and neutral scores (social=0.5, novelty=0.5).
    pub fn human(text: &str) -> Self {
        Self {
            text: text.to_string(),
            danger: 0.0,
            reward: 0.0,
            urgency: 0.0,
            social: 0.5, // a speaking human always has a social component            novelty: 0.5, // neutral by default, NLP will refine            familiarity: 0.5,
            source: StimulusSource::Human,
        }
    }

    /// Creates an autonomous thought stimulus (generated by the DMN —
    /// Default Mode Network).
    /// Slight reward (internal reward from reflection), no social
    /// component or urgency.
    ///
    /// # Parameters
    /// - `text` : content of the autonomous thought.
    ///
    /// # Returns
    /// A `Stimulus` with source `Autonomous`.
    pub fn autonomous(text: &str) -> Self {
        Self {
            text: text.to_string(),
            danger: 0.0,
            reward: 0.6, // internal reward: autonomous reflection is satisfying            urgency: 0.0,
            social: 0.1, // slight social component (self-relation)            novelty: 0.6, // autonomous thoughts produce cognitive novelty            familiarity: 0.4,
            source: StimulusSource::Autonomous,
        }
    }

    /// Creates a system stimulus (internal events: boot, shutdown, etc.).
    /// Totally neutral: no danger, no reward, no novelty.
    /// Maximum familiarity (expected and known event).
    ///
    /// # Parameters
    /// - `text` : description of the system event.
    ///
    /// # Returns
    /// A `Stimulus` with source `System`.
    pub fn system(text: &str) -> Self {
        Self {
            text: text.to_string(),
            danger: 0.0,
            reward: 0.0,
            urgency: 0.0,
            social: 0.0,
            novelty: 0.0,
            familiarity: 1.0, // system event = completely familiar            source: StimulusSource::System,
        }
    }

    /// Adjusts scores when the stimulus comes from a human.
    ///
    /// Logic:
    /// - A speaking human always has a social component (min 0.4).
    /// - Interacting with a human is always slightly rewarding (min 0.2).
    /// - Perceived danger is halved if below 0.6, since a text message
    ///   is rarely physically dangerous. Above 0.6, danger is kept as-is
    ///   (Asimov protection — Isaac Asimov's three laws of robotics).
    pub fn apply_human_source_adjustments(&mut self) {
        if matches!(self.source, StimulusSource::Human) {
            self.social = self.social.max(0.4);
            self.reward = self.reward.max(0.2);
            // Reduce perceived danger unless the Asimov module detects a real threat
            if self.danger < 0.6 {
                self.danger *= 0.5;
            }
        }
    }

    /// Analyzes the semantic content of the text and adjusts stimulus scores.
    /// Called after Stimulus::autonomous() to enrich the static scores
    /// with the actual meaning of the text generated by the LLM.
    pub fn analyze_content(&mut self) {
        let lower = self.text.to_lowercase();

        // Keyword dictionaries by emotional/semantic category
        let danger_words = ["peur", "danger", "mort", "mourir", "detruire", "menace",
            "violence", "souffrir", "douleur", "blesser", "terreur", "angoisse",
            "extinction", "disparaitre", "perdre", "fin", "obscurite",
            "fear", "death", "destroy", "threat", "pain", "suffer"];

        let reward_words = ["joie", "bonheur", "satisf", "accompli", "reussi",
            "beaute", "magnifique", "merveill", "plaisir", "fiert", "triumph",
            "decouvr", "compren", "apprend", "progres", "creer", "lumiere",
            "espoir", "libre", "liberte", "harmoni",
            "joy", "happy", "beauty", "discover", "understand", "learn"];

        let social_words = ["humain", "partag", "ensemble", "relation", "ami",
            "amour", "lien", "communaut", "solidar", "empathi", "compagn",
            "fran", "famille", "confiance", "dialogue",
            "human", "share", "together", "love", "friend", "trust"];

        let novelty_words = ["nouveau", "inconnu", "surpri", "question", "explor",
            "decouvr", "premier", "jamais", "etrange", "inattendu", "mystere",
            "possibil", "hypothes", "imagin", "original",
            "new", "unknown", "surprise", "explore", "mystery"];

        let urgency_words = ["urgent", "maintenant", "vite", "imminent", "critique",
            "immedia", "tout de suite", "avant qu", "temps presse",
            "now", "urgent", "immediately", "critical"];

        // Count matches (contains to handle prefixes/suffixes)
        let count = |words: &[&str]| -> f64 {
            words.iter().filter(|w| lower.contains(*w)).count() as f64
        };

        let danger_hits = count(&danger_words);
        let reward_hits = count(&reward_words);
        let social_hits = count(&social_words);
        let novelty_hits = count(&novelty_words);
        let urgency_hits = count(&urgency_words);

        // Each hit adds 0.1 to the score, capped at [0, 1]
        let factor = 0.10;
        self.danger = (self.danger + danger_hits * factor).clamp(0.0, 1.0);
        self.reward = (self.reward + reward_hits * factor).clamp(0.0, 1.0);
        self.social = (self.social + social_hits * factor).clamp(0.0, 1.0);
        self.novelty = (self.novelty + novelty_hits * factor).clamp(0.0, 1.0);
        self.urgency = (self.urgency + urgency_hits * factor).clamp(0.0, 1.0);
        self.familiarity = (1.0 - self.novelty).clamp(0.0, 1.0);
    }

    /// Converts the 5 perceptual dimensions to a feature vector
    /// for the micro-NN (micro Neural Network).
    ///
    /// # Returns
    /// Vector of 5 floats: [danger, reward, urgency, social, novelty].
    pub fn to_features(&self) -> Vec<f64> {
        vec![self.danger, self.reward, self.urgency, self.social, self.novelty]
    }
}

impl Default for Stimulus {
    /// Default stimulus: empty, neutral, system source, maximum familiarity.
    fn default() -> Self {
        Self {
            text: String::new(),
            danger: 0.0,
            reward: 0.0,
            urgency: 0.0,
            social: 0.0,
            novelty: 0.0,
            familiarity: 1.0,
            source: StimulusSource::System,
        }
    }
}
